x-env-files: &env-files
  - path: .env
  - path: .env.local
    required: false

services:
  api:
    image: csim-api:latest
    restart: unless-stopped
    env_file: *env-files
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: postgres:${POSTGRES_VERSION:-18}-alpine
    env_file: *env-files
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d \"$$POSTGRES_DB\" -U \"$$POSTGRES_USER\""]
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    volumes:
      - database_data:/var/lib/postgresql:rw

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--save",
        "60",
        "1000"
      ]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    image: csim-worker:latest
    restart: unless-stopped
    env_file: *env-files
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  database_data:
  redis_data:
